//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbumImage
    {
        public AbumImage()
        {
            this.BlogDetails = new HashSet<BlogDetail>();
            this.ImageTypes = new HashSet<ImageType>();
            this.InfoProfiles = new HashSet<InfoProfile>();
        }
    
        public int AbumImageID { get; set; }
        public string NameAbum { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeAbum { get; set; }
    
        public virtual ICollection<BlogDetail> BlogDetails { get; set; }
        public virtual ICollection<ImageType> ImageTypes { get; set; }
        public virtual ICollection<InfoProfile> InfoProfiles { get; set; }
    }
}
