//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public string Avatar { get; set; }
        public byte Status { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public byte IsLockedOut { get; set; }
        public System.DateTime LastLockoutTime { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public byte Deleted { get; set; }
        public string Comment { get; set; }
        public string AccountConfirmationToken { get; set; }
        public string AgentId { get; set; }
        public byte IsVerification { get; set; }
        public int MaxClaimDaily { get; set; }
    }
}
