//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogDetail
    {
        public int BlogID { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public Nullable<int> AbumImageID { get; set; }
        public Nullable<int> AmountVote { get; set; }
        public Nullable<int> CategoryBlogID { get; set; }
        public string TitleBlog { get; set; }
        public string AuthorName { get; set; }
        public string SourceBlog { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
    
        public virtual AbumImage AbumImage { get; set; }
        public virtual CategoryBlog CategoryBlog { get; set; }
    }
}
