//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryBlog
    {
        public CategoryBlog()
        {
            this.BlogDetails = new HashSet<BlogDetail>();
        }
    
        public int CategoryBlogID { get; set; }
        public string NameCategory { get; set; }
        public string Descripton { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual ICollection<BlogDetail> BlogDetails { get; set; }
        public virtual Image Image { get; set; }
    }
}
