//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageType
    {
        public int ImageTypeID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> AbumImageID { get; set; }
        public string TypeImage { get; set; }
    
        public virtual AbumImage AbumImage { get; set; }
        public virtual Image Image { get; set; }
    }
}
