//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoProfile
    {
        public InfoProfile()
        {
            this.Skills = new HashSet<Skill>();
            this.WorkExps = new HashSet<WorkExp>();
        }
    
        public int InfoProfileID { get; set; }
        public string Email { get; set; }
        public string NumberPhone { get; set; }
        public string Adress { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string LinkFacebook { get; set; }
        public string Description { get; set; }
        public string Slogan { get; set; }
        public Nullable<int> AbumImageID { get; set; }
    
        public virtual AbumImage AbumImage { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<WorkExp> WorkExps { get; set; }
    }
}
