//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainBlog.Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExp
    {
        public int WorkID { get; set; }
        public Nullable<int> YearExp { get; set; }
        public string Level { get; set; }
        public Nullable<int> Percent { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public string Position { get; set; }
        public Nullable<int> InfoProfileID { get; set; }
    
        public virtual InfoProfile InfoProfile { get; set; }
    }
}
